import { invoke } from '@tauri-apps/api/core'
import { formatSecondsToTime } from '@/lib/formatter'
import { Timer } from '@/app/interfaces/time'
import { TimerActions } from '@/app/hooks/timer'

// Type for the SQLite timer structure
interface SqliteTimer {
  uuid: string
  index_num: number
  name: string
  allows_overrun: boolean
  countdown_duration: number
  state: 'stopped' | 'running' | 'complete' | 'overran' | 'overrunning'
  remaining_seconds: number
  started_at: number | null
  created_at: number
  updated_at: number
}

const getRemainingSeconds = ({
  remaining_seconds,
  started_at,
}: SqliteTimer) => {
  const now = Math.floor(Date.now() / 1000)
  const elapsedTime = now - (started_at ?? now)
  const remaining = Math.floor(remaining_seconds - elapsedTime)
  const negative = remaining < 0

  return {
    remainingSeconds: remaining,
    time: negative
      ? `-${formatSecondsToTime(remaining * -1)}`
      : formatSecondsToTime(remaining),
  }
}

/**
 * Convert SQLite timer format to ProPresenter Timer format
 */
const convertSqliteToTimer = (sqliteTimer: SqliteTimer): Timer => {
  return {
    id: {
      uuid: sqliteTimer.uuid,
      name: sqliteTimer.name,
      index: sqliteTimer.index_num,
    },
    allows_overrun: sqliteTimer.allows_overrun,
    countdown: {
      duration: sqliteTimer.countdown_duration,
    },
    state: sqliteTimer.state,
    // Convert remaining seconds to time format (HH:MM:SS)
    ...getRemainingSeconds(sqliteTimer),
  }
}

/**
 * Fetch all timers from SQLite
 */
export const fetchTimersFromDb = async (): Promise<Timer[]> => {
  try {
    const sqliteTimers = await invoke<SqliteTimer[]>('list_timers')
    return sqliteTimers.map(convertSqliteToTimer)
  } catch (err) {
    console.error('Failed to fetch timers from DB:', err)
    throw new Error('Failed to fetch timers from local database')
  }
}

/**
 * Create a timer in SQLite
 */
export const createTimerInDb = async (
  duration: number,
  name: string
): Promise<Timer> => {
  try {
    const now = Math.floor(Date.now() / 1000)

    // Get current count to determine index
    const count = await invoke<number>('count_timers')

    const sqliteTimer: SqliteTimer = {
      uuid: '', // generated by db
      index_num: count,
      name,
      allows_overrun: true,
      countdown_duration: duration,
      state: 'stopped',
      remaining_seconds: duration,
      started_at: null,
      created_at: now,
      updated_at: now,
    }

    await invoke('create_timer', { timer: sqliteTimer })
    return convertSqliteToTimer(sqliteTimer)
  } catch (err) {
    console.error('Failed to create timer in DB:', err)
    throw new Error('Failed to create timer in local database')
  }
}

/**
 * Update a timer in SQLite
 */
export const editTimerInDb = async (
  duration: number,
  name: string,
  id?: string
): Promise<Timer> => {
  if (!id) throw new Error('Id not set for update')

  try {
    const sqliteTimer: Partial<SqliteTimer> = {
      uuid: id,
      name,
      countdown_duration: duration,
      remaining_seconds: duration,
      allows_overrun: true,
      updated_at: Math.floor(Date.now() / 1000),
    }

    await invoke('update_timer', { timer: sqliteTimer })

    // Fetch the updated timer
    const updated = await invoke<SqliteTimer>('get_timer', { uuid: id })
    return convertSqliteToTimer(updated)
  } catch (err) {
    console.error('Failed to update timer in DB:', err)
    throw new Error('Failed to update timer in local database')
  }
}

/**
 * Delete a timer from SQLite
 */
export const deleteTimerFromDb = async (id?: string): Promise<void> => {
  if (!id) throw new Error('Id not set for delete')

  try {
    await invoke('delete_timer', { uuid: id })
  } catch (err) {
    console.error('Failed to delete timer from DB:', err)
    throw new Error('Failed to delete timer from local database')
  }
}

/**
 * Set timer operation (start, stop, pause, reset) in SQLite
 */
export const setTimerOperationInDb = async (
  operation: string,
  id?: string
): Promise<void> => {
  if (!id) throw new Error('Id not set for operation')

  try {
    const timer = await invoke<SqliteTimer>('get_timer', { uuid: id })
    const now = Math.floor(Date.now() / 1000)

    const updates: Partial<SqliteTimer> = { updated_at: now }

    switch (operation) {
      case 'start':
        updates.state = 'running'
        updates.started_at = now
        break
      case 'stop':
        const elapsedTime = now - (timer.started_at ?? 0)
        updates.state = 'stopped'
        updates.remaining_seconds = Math.floor(
          timer.remaining_seconds - elapsedTime
        )
        break
      case 'reset':
        updates.state = 'stopped'
        updates.remaining_seconds = timer.countdown_duration
        updates.started_at = null
        break
      default:
        throw new Error(`Unknown operation: ${operation}`)
    }
    updates.uuid = id

    await invoke('update_timer', { timer: updates })
  } catch (err) {
    console.error(`Failed to ${operation} timer in DB:`, err)
    throw new Error(`Failed to ${operation} timer in local database`)
  }
}

/**
 * Update timer and perform operation in one call
 */
export const setTimerUpdateOperationInDb = async (
  duration: number,
  name: string,
  operation: string,
  id?: string
): Promise<Timer> => {
  if (!id) throw new Error('Id not set for operation')

  try {
    const now = Math.floor(Date.now() / 1000)
    let state: 'stopped' | 'running' | 'paused' = 'stopped'
    let started_at: number | null = null

    switch (operation) {
      case 'start':
        state = 'running'
        started_at = now
        break
      case 'stop':
        state = 'stopped'
        break
      default:
        state = 'stopped'
    }

    const sqliteTimer: Partial<SqliteTimer> = {
      uuid: id,
      countdown_duration: duration,
      remaining_seconds: duration,
      allows_overrun: true,
      state,
      started_at,
      updated_at: now,
    }

    if (name.length) {
      sqliteTimer.name = name
    }

    await invoke('update_timer', { timer: sqliteTimer })

    const updated = await invoke<SqliteTimer>('get_timer', { uuid: id })
    return convertSqliteToTimer(updated)
  } catch (err) {
    console.error(`Failed to update and ${operation} timer in DB:`, err)
    throw new Error(`Failed to update and ${operation} timer in local database`)
  }
}

/**
 * Perform operation on all timers
 */
export const setAllTimersOperationInDb = async (
  operation: TimerActions
): Promise<void> => {
  try {
    const timers = await invoke<SqliteTimer[]>('list_timers')

    const updates = timers.map(async (timer) => {
      const now = Math.floor(Date.now() / 1000)
      const updateData: Partial<SqliteTimer> = { updated_at: now }

      switch (operation) {
        case 'start':
          updateData.state = 'running'
          updateData.started_at = now
          break
        case 'stop':
          updateData.state = 'stopped'
          updateData.remaining_seconds = timer.countdown_duration
          updateData.started_at = null
          break
        case 'reset':
          updateData.state = 'stopped'
          updateData.remaining_seconds = timer.countdown_duration
          updateData.started_at = null
          break
      }
      updateData.uuid = timer.uuid

      await invoke('update_timer', { timer: updateData })
    })

    await Promise.all(updates)
  } catch (err) {
    console.error(`Failed to ${operation} all timers in DB:`, err)
    throw new Error(`Failed to ${operation} all timers in local database`)
  }
}
