name: Setup Update

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/update.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Next.js build
        run: npm run build:next

      - name: Check if out directory exists
        run: |
          if [ ! -d "out" ]; then
            echo "❌ Directory out does not exist."
            exit 1
          fi

      - name: Create update.zip from out directory
        run: |
          cd out
          zip -r update.zip .
          mv update.zip ..
          echo "✅ Created update.zip"

      - name: Commit and push ZIP file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add update.zip
          git commit -m "Add zipped out directory [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
